function renderReport(el){
  var findings=APP.findings||[];
  var scope=APP.scope||{};
  var now=new Date().toISOString().split('T')[0];
  if(!APP.reportLang)APP.reportLang=APP.lang;

  var h='<div class="sec-hdr">'
    +'<div><div class="sec-title">&#128202; '+t('report_title')+'</div>'
    +'<div class="sec-subtitle">'+t('report_subtitle')+'</div></div>'
    +'<div style="display:flex;gap:8px">'
    +'<button class="btn" onclick="downloadReport()">&#128229; '+t('download_md')+'</button>'
    +'<button class="btn primary" onclick="copyReport()">&#9113; '+t('copy_btn')+'</button>'
    +'</div></div>';

  h+='<div style="padding:12px 20px;border-bottom:1px solid var(--bdr);flex-shrink:0;background:var(--s1);display:flex;gap:12px;flex-wrap:wrap;align-items:center">'
    +'<div class="report-field">'+t('tester_lbl')+' <input id="rpt_tester" value="'+esc(APP.reportTester||'')+'" placeholder="'+esc(t('tester_ph'))+'" oninput="APP.reportTester=this.value" style="width:140px"></div>'
    +'<div class="report-field">'+t('date_lbl')+' <input id="rpt_date" type="date" value="'+esc(APP.reportDate||now)+'" oninput="APP.reportDate=this.value" style="width:130px"></div>'
    +'<div class="report-field">'+t('report_lang_lbl')+' <select id="rpt_lang" onchange="APP.reportLang=this.value;renderReport(document.getElementById(\'secbody\'))" style="background:var(--s2);border:1px solid var(--bdr);border-radius:5px;padding:4px 8px;color:var(--t1);font-size:11px">'
    +'<option value="en"'+(APP.reportLang==='en'?' selected':'')+'>English</option>'
    +'<option value="ar"'+(APP.reportLang==='ar'?' selected':'')+'>العربية</option>'
    +'</select></div>'
    +'<button class="btn sm" onclick="renderReport(document.getElementById(\'secbody\'))">&#8635; '+t('refresh_btn')+'</button>'
    +'</div>';

  h+='<div style="flex:1;overflow-y:auto;padding:16px 20px">';
  h+='<pre class="report-preview" id="report_content"'+(APP.reportLang==='ar'?' dir="rtl" style="text-align:right"':'')+'>'+esc(generateReport())+'</pre>';
  h+='</div>';
  el.innerHTML=h;
}

var REPORT_STRINGS={
  en:{
    h1:'# Penetration Test Report',client:'**Client:**',engtype:'**Engagement Type:**',period:'**Test Period:**',
    to:'to',tester:'**Tester:**',date:'**Report Date:**',execsum:'## Executive Summary',
    during:'During this',engagement_for:'engagement for',vulns_identified:'security vulnerabilities were identified',
    no_vulns:'no security vulnerabilities were identified',critical_w:'Critical',high_sev_w:'High-severity',
    immediate:'issues require immediate remediation.',remain_open:'findings remain Open and require remediation before closure.',
    all_remediated:'All findings have been remediated.',scope_lbl:'**Scope:**',target_systems:'[Target systems]',
    findings_summary:'## Findings Summary',col_num:'#',col_sev:'Severity',col_cvss:'CVSS',col_finding:'Finding',col_status:'Status',
    detailed_findings:'## Detailed Findings',severity_lbl:'**Severity:**',cvss_vector_lbl:'**CVSS Vector:**',
    affected_lbl:'**Affected:**',mitre_lbl:'**MITRE ATT&CK:**',status_lbl:'**Status:**',description_h:'#### Description',
    business_impact_h:'#### Business Impact',evidence_h:'#### Evidence',remediation_h:'#### Remediation',
    engagement_notes:'## Engagement Notes',attack_chain:'## Attack Chain Narrative',footer:'*Generated by PenTest Pro — Elite Framework*',
    tester_ph:'[Tester Name]',client_ph:'[Client Name]',type_ph:'[Test Type]',start_ph:'[Start]',end_ph:'[End]',
    untitled:'Untitled',open_w:'Open',pentest_w:'penetration test'
  },
  ar:{
    h1:'# تقرير اختبار الاختراق',client:'**العميل:**',engtype:'**نوع المهمة:**',period:'**فترة الاختبار:**',
    to:'إلى',tester:'**الفاحص:**',date:'**تاريخ التقرير:**',execsum:'## الملخص التنفيذي',
    during:'خلال',engagement_for:'لصالح',vulns_identified:'تم اكتشاف ثغرات أمنية',
    no_vulns:'لم يتم اكتشاف أي ثغرات أمنية',critical_w:'حرجة',high_sev_w:'عالية الخطورة',
    immediate:'تتطلب إصلاحاً فورياً.',remain_open:'نتائج لا تزال مفتوحة وتتطلب إصلاحاً قبل الإغلاق.',
    all_remediated:'تم إصلاح جميع الثغرات.',scope_lbl:'**النطاق:**',target_systems:'[الأنظمة المستهدفة]',
    findings_summary:'## ملخص الثغرات',col_num:'#',col_sev:'الخطورة',col_cvss:'CVSS',col_finding:'الثغرة',col_status:'الحالة',
    detailed_findings:'## تفاصيل الثغرات',severity_lbl:'**الخطورة:**',cvss_vector_lbl:'**متجه CVSS:**',
    affected_lbl:'**المتأثر:**',mitre_lbl:'**أسلوب MITRE ATT&CK:**',status_lbl:'**الحالة:**',description_h:'#### الوصف',
    business_impact_h:'#### الأثر على الأعمال',evidence_h:'#### الدليل',remediation_h:'#### الإصلاح',
    engagement_notes:'## ملاحظات المهمة',attack_chain:'## سرد سلسلة الهجوم',footer:'*تم إنشاؤه بواسطة PenTest Pro — الإطار الاحترافي*',
    tester_ph:'[اسم الفاحص]',client_ph:'[اسم العميل]',type_ph:'[نوع الاختبار]',start_ph:'[البداية]',end_ph:'[النهاية]',
    untitled:'بدون عنوان',open_w:'مفتوحة',pentest_w:'اختبار اختراق'
  }
};

function generateReport(){
  var findings=APP.findings||[];
  var scope=APP.scope||{};
  var L=REPORT_STRINGS[APP.reportLang||APP.lang||'en'];
  var tester=APP.reportTester||L.tester_ph;
  var date=APP.reportDate||(new Date().toISOString().split('T')[0]);
  var client=scope.client||APP.eng||L.client_ph;
  var sevOrder={Critical:0,High:1,Medium:2,Low:3,Info:4};
  var sorted=findings.slice().sort(function(a,b){return (sevOrder[a.severity]||4)-(sevOrder[b.severity]||4);});

  var sevCounts={Critical:0,High:0,Medium:0,Low:0,Info:0};
  findings.forEach(function(f){sevCounts[f.severity]=(sevCounts[f.severity]||0)+1;});
  var openCount=findings.filter(function(f){return f.status==='Open';}).length;

  var out=L.h1+'\n';
  out+='\n'+L.client+' '+client;
  out+='\n'+L.engtype+' '+(scope.type||L.type_ph);
  out+='\n'+L.period+' '+(scope.start||L.start_ph)+' '+L.to+' '+(scope.end||L.end_ph);
  out+='\n'+L.tester+' '+tester;
  out+='\n'+L.date+' '+date;
  out+='\n\n---\n';
  out+='\n'+L.execsum+'\n';
  out+='\n'+L.during+' '+(scope.type||L.pentest_w)+' '+L.engagement_for+' **'+client+'**, ';
  out+=(findings.length?findings.length+' '+L.vulns_identified:L.no_vulns)+'. ';
  if(sevCounts.Critical)out+=sevCounts.Critical+' '+L.critical_w;
  if(sevCounts.High)out+=(sevCounts.Critical?(APP.reportLang==='ar'?' و ':' and '):'')+sevCounts.High+' '+L.high_sev_w;
  if(sevCounts.Critical||sevCounts.High)out+=' '+L.immediate+' ';
  out+=(openCount>0?openCount+' '+L.remain_open:L.all_remediated);
  out+='\n\n'+L.scope_lbl+' '+(scope.targets&&scope.targets.length?scope.targets.join(', '):L.target_systems);
  out+='\n\n---\n';

  out+='\n'+L.findings_summary+'\n';
  out+='\n| '+L.col_num+' | '+L.col_sev+' | '+L.col_cvss+' | '+L.col_finding+' | '+L.col_status+' |\n';
  out+=  '|---|----------|------|---------|--------|\n';
  sorted.forEach(function(f,i){
    var sevDisp=t('sev_'+(f.severity||'').toLowerCase())||f.severity;
    var statDisp=f.status==='Fixed'?t('fixed_lbl'):f.status==='Risk Accepted'?t('risk_accepted_lbl'):(f.status||L.open_w);
    out+='| F'+(i+1)+' | '+sevDisp+' | '+(f.cvss_score||'—')+' | '+(f.title||L.untitled)+' | '+statDisp+' |\n';
  });

  out+='\n---\n\n'+L.detailed_findings+'\n';
  sorted.forEach(function(f,i){
    var sevDisp=t('sev_'+(f.severity||'').toLowerCase())||f.severity;
    var statDisp=f.status==='Fixed'?t('fixed_lbl'):f.status==='Risk Accepted'?t('risk_accepted_lbl'):(f.status||L.open_w);
    out+='\n### F'+(i+1)+': '+(f.title||L.untitled)+'\n';
    out+='\n'+L.severity_lbl+' '+sevDisp+(f.cvss_score?' (CVSS '+f.cvss_score+')':'');
    if(f.cvss_vector)out+='  \n'+L.cvss_vector_lbl+' `'+f.cvss_vector+'`';
    if(f.affected)out+='  \n'+L.affected_lbl+' `'+f.affected+'`';
    if(f.mitre)out+='  \n'+L.mitre_lbl+' ['+f.mitre+' - '+(f.mitre_name||f.mitre)+'](https://attack.mitre.org/techniques/'+f.mitre.replace('.','/')+')';
    out+='  \n'+L.status_lbl+' '+statDisp;
    if(f.description)out+='\n\n'+L.description_h+'\n'+f.description;
    if(f.business_impact)out+='\n\n'+L.business_impact_h+'\n'+f.business_impact;
    if(f.evidence)out+='\n\n'+L.evidence_h+'\n```\n'+f.evidence+'\n```';
    if(f.remediation)out+='\n\n'+L.remediation_h+'\n'+f.remediation;
    out+='\n\n---';
  });

  // Notes from framework
  var noteKeys=Object.keys(APP.notes||{});
  if(noteKeys.length){
    out+='\n\n'+L.engagement_notes+'\n';
    noteKeys.forEach(function(k){
      if(APP.notes[k]&&APP.notes[k].trim()){
        out+='\n### '+k.replace('note_','').toUpperCase()+'\n'+APP.notes[k]+'\n';
      }
    });
  }

  if(APP.kcNarr){
    out+='\n\n'+L.attack_chain+'\n'+APP.kcNarr+'\n';
  }

  out+='\n\n---\n'+L.footer;
  return out;
}

function copyReport(){
  copy(generateReport(),document.querySelector('.sec-hdr .btn.primary'));
}

function downloadReport(){
  var content=generateReport();
  var blob=new Blob([content],{type:'text/markdown'});
  var url=URL.createObjectURL(blob);
  var a=document.createElement('a');
  var client=(APP.scope&&APP.scope.client?APP.scope.client:APP.eng||'report').replace(/\s+/g,'-').toLowerCase();
  a.href=url;a.download='pentest-'+client+'-'+(new Date().toISOString().split('T')[0])+'.md';
  document.body.appendChild(a);a.click();document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
