function renderReport(el){
  var findings=APP.findings||[];
  var scope=APP.scope||{};
  var now=new Date().toISOString().split('T')[0];

  var h='<div class="sec-hdr">'
    +'<div><div class="sec-title">&#128202; Report Generator</div>'
    +'<div class="sec-subtitle">Auto-generated from your findings and scope data</div></div>'
    +'<div style="display:flex;gap:8px">'
    +'<button class="btn" onclick="downloadReport()">&#128229; Download .md</button>'
    +'<button class="btn primary" onclick="copyReport()">&#9113; Copy</button>'
    +'</div></div>';

  h+='<div style="padding:12px 20px;border-bottom:1px solid var(--bdr);flex-shrink:0;background:var(--s1);display:flex;gap:12px;flex-wrap:wrap;align-items:center">'
    +'<div class="report-field">Tester: <input id="rpt_tester" value="'+esc(APP.reportTester||'')+'" placeholder="Your Name" oninput="APP.reportTester=this.value" style="width:140px"></div>'
    +'<div class="report-field">Date: <input id="rpt_date" type="date" value="'+esc(APP.reportDate||now)+'" oninput="APP.reportDate=this.value" style="width:130px"></div>'
    +'<button class="btn sm" onclick="renderReport(document.getElementById(\'secbody\'))">&#8635; Refresh</button>'
    +'</div>';

  h+='<div style="flex:1;overflow-y:auto;padding:16px 20px">';
  h+='<pre class="report-preview" id="report_content">'+esc(generateReport())+'</pre>';
  h+='</div>';
  el.innerHTML=h;
}

function generateReport(){
  var findings=APP.findings||[];
  var scope=APP.scope||{};
  var tester=APP.reportTester||'[Tester Name]';
  var date=APP.reportDate||(new Date().toISOString().split('T')[0]);
  var client=scope.client||APP.eng||'[Client Name]';
  var sevOrder={Critical:0,High:1,Medium:2,Low:3,Info:4};
  var sorted=findings.slice().sort(function(a,b){return (sevOrder[a.severity]||4)-(sevOrder[b.severity]||4);});

  var sevCounts={Critical:0,High:0,Medium:0,Low:0,Info:0};
  findings.forEach(function(f){sevCounts[f.severity]=(sevCounts[f.severity]||0)+1;});
  var openCount=findings.filter(function(f){return f.status==='Open';}).length;

  var out='# Penetration Test Report\n';
  out+='\n**Client:** '+client;
  out+='\n**Engagement Type:** '+(scope.type||'[Test Type]');
  out+='\n**Test Period:** '+(scope.start||'[Start]')+' to '+(scope.end||'[End]');
  out+='\n**Tester:** '+tester;
  out+='\n**Report Date:** '+date;
  out+='\n\n---\n';
  out+='\n## Executive Summary\n';
  out+='\nDuring this '+( scope.type||'penetration test')+' engagement for **'+client+'**, ';
  out+=(findings.length?findings.length+' security vulnerabilities were identified':'no security vulnerabilities were identified')+'. ';
  if(sevCounts.Critical)out+=sevCounts.Critical+' Critical';
  if(sevCounts.High)out+=(sevCounts.Critical?' and ':'')+sevCounts.High+' High-severity';
  if(sevCounts.Critical||sevCounts.High)out+=' issues require immediate remediation. ';
  out+=(openCount>0?openCount+' findings remain Open and require remediation before closure.':'All findings have been remediated.');
  out+='\n\n**Scope:** '+(scope.targets&&scope.targets.length?scope.targets.join(', '):'[Target systems]');
  out+='\n\n---\n';

  out+='\n## Findings Summary\n';
  out+='\n| # | Severity | CVSS | Finding | Status |\n';
  out+=  '|---|----------|------|---------|--------|\n';
  sorted.forEach(function(f,i){
    out+='| F'+(i+1)+' | '+f.severity+' | '+(f.cvss_score||'—')+' | '+(f.title||'Untitled')+' | '+(f.status||'Open')+' |\n';
  });

  out+='\n---\n\n## Detailed Findings\n';
  sorted.forEach(function(f,i){
    out+='\n### F'+(i+1)+': '+(f.title||'Untitled')+'\n';
    out+='\n**Severity:** '+f.severity+(f.cvss_score?' (CVSS '+f.cvss_score+')':'');
    if(f.cvss_vector)out+='  \n**CVSS Vector:** `'+f.cvss_vector+'`';
    if(f.affected)out+='  \n**Affected:** `'+f.affected+'`';
    if(f.mitre)out+='  \n**MITRE ATT&CK:** ['+f.mitre+' - '+(f.mitre_name||f.mitre)+'](https://attack.mitre.org/techniques/'+f.mitre.replace('.','/')+')';
    out+='  \n**Status:** '+( f.status||'Open');
    if(f.description)out+='\n\n#### Description\n'+f.description;
    if(f.business_impact)out+='\n\n#### Business Impact\n'+f.business_impact;
    if(f.evidence)out+='\n\n#### Evidence\n```\n'+f.evidence+'\n```';
    if(f.remediation)out+='\n\n#### Remediation\n'+f.remediation;
    out+='\n\n---';
  });

  // Notes from framework
  var noteKeys=Object.keys(APP.notes||{});
  if(noteKeys.length){
    out+='\n\n## Engagement Notes\n';
    noteKeys.forEach(function(k){
      if(APP.notes[k]&&APP.notes[k].trim()){
        out+='\n### '+k.replace('note_','').toUpperCase()+'\n'+APP.notes[k]+'\n';
      }
    });
  }

  if(APP.kcNarr){
    out+='\n\n## Attack Chain Narrative\n'+APP.kcNarr+'\n';
  }

  out+='\n\n---\n*Generated by PenTest Pro — Elite Framework*';
  return out;
}

function copyReport(){
  copy(generateReport(),document.querySelector('.sec-hdr .btn.primary'));
}

function downloadReport(){
  var content=generateReport();
  var blob=new Blob([content],{type:'text/markdown'});
  var url=URL.createObjectURL(blob);
  var a=document.createElement('a');
  var client=(APP.scope&&APP.scope.client?APP.scope.client:APP.eng||'report').replace(/\s+/g,'-').toLowerCase();
  a.href=url;a.download='pentest-'+client+'-'+(new Date().toISOString().split('T')[0])+'.md';
  document.body.appendChild(a);a.click();document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
